export enum CancellationReasonCode {
  CLIENTE_CAMBIO_PLANES = 'CLIENTE_CAMBIO_PLANES',
  CLIENTE_TIEMPO_ESPERA = 'CLIENTE_TIEMPO_ESPERA',
  CLIENTE_OTRO = 'CLIENTE_OTRO',
  CONDUCTOR_TRAFICO = 'CONDUCTOR_TRAFICO',
  CONDUCTOR_VEHICULO = 'CONDUCTOR_VEHICULO',
  CONDUCTOR_EMERGENCIA = 'CONDUCTOR_EMERGENCIA',
  CONDUCTOR_UBICACION = 'CONDUCTOR_UBICACION',
  CONDUCTOR_OTRO = 'CONDUCTOR_OTRO',
}
